### ISSUE TITLE
Using diverging scale with discrete data

### ISSUE THREAD

**Issue by larmarange** [nfrerebeau/khroma#7]
It would be great to have the option to use diverging colors scales with discrete data, by adding functions such as `scale_fill_discretePRGn()`

**Comment by nfrerebeau** [comment]
I just modified the `scale_*` functions for the diverging color schemes. Now you can use `scale_fill_PRGn(discrete = TRUE)`.

**Comment by larmarange** [comment]
Thanks a lot :-)
